<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tarian Yang Ditawarkan_bg-white rounded</name>
   <tag></tag>
   <elementGuidId>0560941d-7035-4477-b214-d536adca5dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bg-white.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detailSanggar']/div/div[4]/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/i-tallenta/image/fetch/f_auto,q_auto,c_fill/https://res.cloudinary.com/i-tallenta/image/upload/v1626948176/sanggar/eurilucm9xaopv0219um.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white rounded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailSanggar&quot;)/div[@class=&quot;overflow-auto container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4&quot;]/div[@class=&quot;mb-5 card card-hover col-md-3 col-12&quot;]/div[@class=&quot;card-deck&quot;]/div[@class=&quot;card rounded-circle&quot;]/img[@class=&quot;bg-white rounded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailSanggar']/div/div[4]/div/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='image']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
