<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_dibayar_rounded</name>
   <tag></tag>
   <elementGuidId>85d6e1b3-8b91-48c0-ac8c-edb638cc594e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order-264 > div.row.justify-content-lg-between.row-cols-2.row-cols-sm-2.row-cols-md-2.row-cols-lg-3.row-cols-xl-3.no-gutters > div.my-auto.mx-auto.align-self-lg-center.col-sm-3.col-md-3.col-lg-3.col-xl-3 > a > img.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-264']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/i-tallenta/image/fetch/f_auto,q_auto,w_200,c_fill/https://res.cloudinary.com/i-tallenta/image/upload/v1625637585/sanggar/nl3hcbaedsi8fst3xbpo.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 640px) 30vw, (max-width: 768px) 20vw, 200px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/i-tallenta/image/fetch/f_auto,q_auto,w_192,c_fill/https://res.cloudinary.com/i-tallenta/image/upload/v1625637585/sanggar/nl3hcbaedsi8fst3xbpo.jpg 192w, https://res.cloudinary.com/i-tallenta/image/fetch/f_auto,q_auto,w_154,c_fill/https://res.cloudinary.com/i-tallenta/image/upload/v1625637585/sanggar/nl3hcbaedsi8fst3xbpo.jpg 154w, https://res.cloudinary.com/i-tallenta/image/fetch/f_auto,q_auto,w_200,c_fill/https://res.cloudinary.com/i-tallenta/image/upload/v1625637585/sanggar/nl3hcbaedsi8fst3xbpo.jpg 200w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-264&quot;)/div[@class=&quot;row justify-content-lg-between row-cols-2 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 no-gutters&quot;]/div[@class=&quot;my-auto mx-auto align-self-lg-center col-sm-3 col-md-3 col-lg-3 col-xl-3&quot;]/a[1]/img[@class=&quot;rounded&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-264']/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
