<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bantul_card-img (1)</name>
   <tag></tag>
   <elementGuidId>150da461-7b76-433b-9a37-e69fb390465c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/i-tallenta/image/upload/v1625636386/sanggar/ohj8sqtvkckpex1katsf.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;explorePage&quot;)/div[@class=&quot;mt-5 container-fluid&quot;]/div[@class=&quot;m-lg-5&quot;]/div[@class=&quot;row text-center mt-3 d-block&quot;]/div[@class=&quot;m-lg-0 m-md-2 m-sm-3 m-5&quot;]/div[@class=&quot;row mb-3 justify-content-center row-cols-12&quot;]/div[@class=&quot;mb-3 card-deck&quot;]/div[@id=&quot;sanggarList&quot;]/a[@class=&quot;text-decoration-none text-dark&quot;]/img[@class=&quot;card-img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='sanggarList']/a/img)[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/i-tallenta/image/upload/v1625636386/sanggar/ohj8sqtvkckpex1katsf.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
